variable "availability_domain" {}
variable "compartment_ocid" {}
variable "subnet_id" {}
variable "instance_name" {}
variable "instance_shape" {}
variable "image_id" {}
variable "public_edge_node" {}
variable "ssh_public_key" {}
variable "image_label" {}
variable "oke_cluster_id" {}
variable "nodepool_id" {}
variable "repo_name" {}
variable "registry" {}
variable "registry_user" {}
variable "secret_id" {}
variable "tenancy_ocid" {}
variable "admin_db_user" {}
variable "admin_db_password" {}
variable "db_user" {}
variable "db_password" {}
variable "db_name" {}
variable "db_ip" {}
variable "db_port" {}
variable "namespace" {}
variable "kube_label" {}
variable "user_data" {}

