variable transcoder_depends_on {}
variable "instance_ip" {}
variable "compartment_ocid" {}
variable "ssh_public_key" {}
variable "ssh_private_key" {}
variable "cluster_id" {}
variable "nodepool_id" {}
variable "nodepool_label" {}
variable "region" {}
variable "registry" {}
variable "repo_name" {}
variable "registry_user" {}
variable "image_label" {}
variable "secret_id" {}
variable "tenancy_ocid" {}
variable "namespace" {}
variable "kube_label" {}
variable "admin_db_user" {}
variable "admin_db_password" {}
variable "db_user" {}
variable "db_password" {}
variable "db_name" {}
variable "db_ip" {}
variable "db_port" {}
variable "src_bucket" {}
variable "dst_bucket" {}
variable "stream_ocid" {}
variable "stream_endpoint" {}
variable "ffmpeg_config" {}
variable "ffmpeg_stream_map" {}
variable "hls_stream_url" {}
variable "cpu_request_per_job" {}
variable "cluster_autoscaling" {}
variable "oci_cluster_autoscaler_image" {}
variable "min_worker_nodes" {}
variable "max_worker_nodes" {}



